image: oven/bun:alpine
 
stages:
    - prepare
    - build
    - deploy

cache:
  paths:
    - ./front/website/node_modules/
 
build:
  stage: build
  only:
    - master
    - dev
  before_script:
    #Website
    - cd ./front/website    
    - rm -rf dist    
    - CI=false bun install
    - cd ../..
    #Compress
    - apk add --no-cache brotli
    - apk add --no-cache zstd
  script:
    #Website
    - cd ./front/website  
    - CI=false bun run build
    - cd ../..
    - mkdir build
    - mv ./front/website/dist/* build  
    #Compress
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\)$' -exec gzip -f -k -9 {} \;
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\)$' -exec brotli -f -k -Z {} \;
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|xml\|json\|mjs\|svg\|yaml\|yml\|toml\|css\)$' -exec zstd -f -k --ultra -22 -q {} \;
  artifacts:
        paths:
          - build


deploy:staging:
  stage: deploy
  only:
    - dev
  dependencies:
    - build
  environment:
    name: dev/$CI_COMMIT_REF_NAME
    url: "https://antfor.gitlab.io/-/antfor.gitlab.io/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  script:
    - mkdir public
    - mv build/* public
    - echo -e "https://antfor.gitlab.io/-/antfor.gitlab.io/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  variables:    
    PUBLIC_URL: "/-/antfor.gitlab.io/-/jobs/$CI_JOB_ID/artifacts/public/"
  artifacts:
    paths:
      - public

 
pages:
  stage: deploy
  only:
    - master
  dependencies:
    - build
  environment: Production
  script:
    - mkdir public
    - mv build/* public
  variables:    
    PUBLIC_URL: "/"
  artifacts:
    paths:
      - public

