image: node:latest
 
cache:
  paths:
    - ./front/ui/node_modules/
 
before_script:
  - cd ./front/ui/rcc    # enter the React app directory
  - rm -rf build     # remove the existing build
  - CI=false npm install     # install required packages
 
pages:
  stage: deploy
  environment: Production
  script:
    - CI=false npm run build     # build the React app, set CI=false because CI=true treats all warnings as errors
    #- cp build/index.html build/404.html     # reroute to index
    - ls
    - mv ./front/ui/build/* ./public/project/rcc   # move build contents to new /public directory
    - export